name: Create locale PR
on:
  push:
    branches:
      - devel

jobs:
  pull-request:
    if: "!contains(github.event.head_commit.message, '[skip deploy]') && !startsWith(github.event.head_commit.message, 'ci: bumps version to')"
    runs-on: ubuntu-latest
    outputs:
      created-pr: ${{ steps.pr-created.outputs.created }}
      diff: ${{ steps.diff.outputs.file_changed }}

    steps:
    - name: Checkout source code
      uses: 'actions/checkout@v2'
      with:
        ref: ${{ github.ref }}

    - name: Install diff tool
      run: |
        curl --silent --location https://git.io/JYfAY | bash

    - name: Request locale file and diff
      id: diff
      continue-on-error: true
      run: |
        curl "https://link.storjshare.io/s/jwn76z454uywl3afnx4cjypx4lba/demo-bucket/en.yml?download=1" > config/locales/en.new.yml

        {
          dyff between --set-exit-code config/locales/en.new.yml config/locales/en.yml
        } || {
          rm config/locales/en.yml
          mv config/locales/en.new.yml config/locales/en.yml
          echo 'file_changed=true' >> $GITHUB_OUTPUT
        }
        
    - name: Create pull request
      if: steps.diff.outputs.file_changed == 'true'
      id: pull-request
      uses: repo-sync/pull-request@master
      with:
        destination_branch: "master"
        pr_title: "Update main locale"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check PR creation
      id: pr-created
      env:
        PR_NUMBER: ${{steps.pull-request.outputs.pr_number}}
      run: |
        if [[ -n "$PR_NUMBER" ]]
        then
          echo 'created=true' >> $GITHUB_OUTPUT
        else
          echo 'created=false' >> $GITHUB_OUTPUT
        fi
